version: '2'
services:
  web:
    build: .
    links:
      - mongo
    ports:
      - "3000:3000"
      - "3001:3001"
      - "8080:8080"
  mongo:
    image: mongo:latest
    restart: always
    mem_limit: 512m
  mongoexpress:
    image: yeasy/mongo-express
    ports:
      - "8081:8081"
    links:
      - mongo
    mem_limit: 128m
    depends_on:
      - mongo
    environment:
      - WEB_USER='user'
      - WEB_PASS='pass'
    command: sh -c 'sleep 10 && tini -- node app'
